-- 7日・49日・98日移動平均カラム追加
ALTER TABLE stocks
    ADD COLUMN IF NOT EXISTS ma7  NUMERIC(10,2),
    ADD COLUMN IF NOT EXISTS ma49 NUMERIC(10,2),
    ADD COLUMN IF NOT EXISTS ma98 NUMERIC(10,2);

ALTER TABLE stock_technical_daily
    ADD COLUMN IF NOT EXISTS ma7  NUMERIC(10,2),
    ADD COLUMN IF NOT EXISTS ma49 NUMERIC(10,2),
    ADD COLUMN IF NOT EXISTS ma98 NUMERIC(10,2);
